(include "src/tokenizer.scm")
(include "src/parser")
(include "src/interpreter")
(import marrow-tokenizer marrow-parser marrow-interpreter)

(let* ((tokens (tokenize "((fn (a b) (+ a b)) 1990 9)"))
       (tree (parse tokens))
       (value (interpret tree)))
  (display tokens)
  (display "\n\n")
  (display tree)
  (display "\n\n")
  (display value))
